# Generated by Django 5.2.4 on 2025-07-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania')], max_length=100)),
                ('bishop_name', models.CharField(max_length=200)),
                ('bishop_phone', models.CharField(blank=True, max_length=20)),
                ('bishop_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diocese',
                'verbose_name_plural': 'Dioceses',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pastorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pastor_name', models.CharField(max_length=200)),
                ('pastor_phone', models.CharField(blank=True, max_length=20)),
                ('pastor_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastorates', to='church_structure.diocese')),
            ],
            options={
                'verbose_name': 'Pastorate',
                'verbose_name_plural': 'Pastorates',
                'ordering': ['diocese', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('head_teacher_name', models.CharField(max_length=200)),
                ('head_teacher_phone', models.CharField(blank=True, max_length=20)),
                ('head_teacher_email', models.EmailField(blank=True, max_length=254)),
                ('assistant_teachers', models.TextField(blank=True, help_text='List additional church teachers, one per line')),
                ('service_times', models.TextField(blank=True, help_text='Service schedule information')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pastorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='church_structure.pastorate')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'ordering': ['pastorate', 'name'],
            },
        ),
    ]
