# Generated by Django 5.2.4 on 2025-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('location', models.CharField(help_text='Location (city, country)', max_length=200)),
                ('map_link', models.URLField(blank=True, help_text='Google Maps link for exact church location')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_times', models.CharField(choices=[('6:00 AM Saturday', '6:00 AM Saturday'), ('9:00 AM Saturday', '9:00 AM Saturday'), ('12:00 NOON Saturday', '12:00 NOON Saturday'), ('3:00 PM Saturday', '3:00 PM Saturday')], default='9:00 AM Saturday', help_text='Service time on Saturday', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('rich_description', models.TextField(blank=True, help_text='Rich HTML content for detailed description')),
                ('is_mission_church', models.BooleanField(default=False, verbose_name='Mission Church')),
                ('is_diocesan_church', models.BooleanField(default=False, verbose_name='Diocesan Church')),
                ('is_headquarter_church', models.BooleanField(default=False, verbose_name='Headquarter Church')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'ordering': ['pastorate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('Democratic Republic of Congo', 'Democratic Republic of Congo'), ('Egypt', 'Egypt'), ('Ethiopia', 'Ethiopia'), ('France', 'France'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Lebanon', 'Lebanon'), ('Malaysia', 'Malaysia'), ('Morocco', 'Morocco'), ('Netherlands', 'Netherlands'), ('Nigeria', 'Nigeria'), ('Pakistan', 'Pakistan'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Rwanda', 'Rwanda'), ('Saudi Arabia', 'Saudi Arabia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sudan', 'Sudan'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syria', 'Syria'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rich_description', models.TextField(blank=True, help_text='Rich HTML content for detailed description')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diocese',
                'verbose_name_plural': 'Dioceses',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pastorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rich_description', models.TextField(blank=True, help_text='Rich HTML content for detailed description')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pastorate',
                'verbose_name_plural': 'Pastorates',
                'ordering': ['diocese', 'name'],
            },
        ),
    ]
