# Generated by Django 5.2.4 on 2025-08-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='diocese',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pastorate',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
