# Generated by Django 5.2.4 on 2025-09-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_structure', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='head_teacher',
            field=models.ForeignKey(blank=True, help_text='Search and select a member as head teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches_as_head_teacher', to='members.member'),
        ),
        migrations.AddField(
            model_name='church',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Search and select up to 12 additional teachers', related_name='churches_as_teacher', to='members.member'),
        ),
        migrations.AddField(
            model_name='diocese',
            name='bishop',
            field=models.ForeignKey(blank=True, help_text='Search and select a member as bishop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dioceses_as_bishop', to='members.member'),
        ),
        migrations.AddField(
            model_name='pastorate',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastorates', to='church_structure.diocese'),
        ),
        migrations.AddField(
            model_name='pastorate',
            name='pastor',
            field=models.ForeignKey(blank=True, help_text='Search and select a member as pastor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastorates_as_pastor', to='members.member'),
        ),
        migrations.AddField(
            model_name='church',
            name='pastorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='church_structure.pastorate'),
        ),
    ]
