# Generated by Django 5.2.4 on 2025-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0003_populate_unique_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='pastorate',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
