# Generated by Django 5.2.4 on 2025-08-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0004_alter_church_slug_alter_diocese_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='identifier',
            field=models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='diocese',
            name='identifier',
            field=models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pastorate',
            name='identifier',
            field=models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True),
        ),
    ]
