# Generated by Django 5.2.4 on 2025-08-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0007_update_leadership_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diocese',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('Democratic Republic of Congo', 'Democratic Republic of Congo'), ('Egypt', 'Egypt'), ('Ethiopia', 'Ethiopia'), ('France', 'France'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Lebanon', 'Lebanon'), ('Malaysia', 'Malaysia'), ('Morocco', 'Morocco'), ('Netherlands', 'Netherlands'), ('Nigeria', 'Nigeria'), ('Pakistan', 'Pakistan'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Rwanda', 'Rwanda'), ('Saudi Arabia', 'Saudi Arabia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sudan', 'Sudan'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syria', 'Syria'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=100),
        ),
    ]
