# Generated by Django 5.2.4 on 2025-08-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0009_update_church_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='location',
            field=models.CharField(help_text='Location (city, country)', max_length=200),
        ),
    ]
