
# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0010_alter_church_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='rich_description',
            field=models.TextField(blank=True, help_text='Rich HTML content for detailed description'),
        ),
        migrations.AddField(
            model_name='pastorate',
            name='rich_description',
            field=models.TextField(blank=True, help_text='Rich HTML content for detailed description'),
        ),
        migrations.AddField(
            model_name='church',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the church'),
        ),
        migrations.AddField(
            model_name='church',
            name='rich_description',
            field=models.TextField(blank=True, help_text='Rich HTML content for detailed description'),
        ),
    ]
