
# Generated by Django 5.2.4 on 2025-09-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0011_add_rich_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='is_diosen_church',
            new_name='is_diocesan_church',
        ),
    ]
