# Generated by Django 5.2.4 on 2025-09-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0012_rename_is_diosen_church_to_is_diocesan_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='is_diocesan_church',
            field=models.BooleanField(default=False, verbose_name='Diocesan Church'),
        ),
    ]
