# Generated by Django 5.2.4 on 2025-07-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('supplies', 'Supplies'), ('equipment', 'Equipment'), ('ministry', 'Ministry'), ('outreach', 'Outreach'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Offering Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('donor_name', models.CharField(blank=True, help_text='For anonymous donations', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.offeringcategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
