# Generated by Django 5.2.4 on 2025-11-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='custom_emails',
            field=models.JSONField(blank=True, default=list, help_text='Custom email addresses for sending'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'All Members'), ('youth', 'Youth Only'), ('adult', 'Adults Only'), ('elder', 'Elders Only'), ('clergy', 'Clergy Only'), ('staff', 'Staff Only'), ('ordained', 'Ordained Members Only'), ('diocese', 'Specific Diocese'), ('pastorate', 'Specific Pastorate'), ('church', 'Specific Church'), ('custom', 'Custom Filter'), ('custom_emails', 'Custom Email Addresses')], default='all', max_length=50),
        ),
        migrations.CreateModel(
            name='EmailCampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Document or photo attachment', upload_to='email_attachments/%Y/%m/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME content type', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_system.emailcampaign')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
