# Generated by Django 5.2.4 on 2025-11-21 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_structure', '0002_initial'),
        ('email_system', '0002_emailcampaign_custom_emails_and_more'),
        ('members', '0004_remove_member_aunt_remove_member_brother_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, help_text='Auto-generated unique identifier (e.g., RUWE-VSTR-XXXX-XXXX)', max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('age_group', models.CharField(choices=[('child', 'Child (0-12)'), ('youth', 'Youth (13-25)'), ('adult', 'Adult (26-59)'), ('elder', 'Elder (60+)')], default='adult', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True, help_text='Physical address/location')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('is_dean_visitor', models.BooleanField(default=False, help_text='Visitor came during Dean/Headquarters gathering', verbose_name='Dean/Headquarters Visitor')),
                ('first_visit_date', models.DateField(default=django.utils.timezone.now)),
                ('referral_source', models.CharField(choices=[('member', 'Church Member'), ('friend', 'Friend/Family'), ('social_media', 'Social Media'), ('website', 'Website'), ('passing_by', 'Passing By'), ('event', 'Event/Crusade'), ('other', 'Other')], default='other', max_length=50)),
                ('invited_by_name', models.CharField(blank=True, help_text='Name of person who invited (if not a member)', max_length=200)),
                ('interested_in_membership', models.BooleanField(default=False)),
                ('prayer_request', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True, help_text='Ministry interests (Youth, Choir, etc.)')),
                ('converted_to_member', models.BooleanField(default=False)),
                ('converted_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active visitor (not converted yet)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this visitor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, help_text='Church where visitor came', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='church_structure.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
                ('diocese', models.ForeignKey(blank=True, help_text='Diocese (auto-filled from church)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='church_structure.diocese')),
                ('invited_by_member', models.ForeignKey(blank=True, help_text='Member who invited this visitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_visitors', to='members.member')),
                ('member_profile', models.ForeignKey(blank=True, help_text='Link to member profile if converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_visitor', to='members.member')),
                ('pastorate', models.ForeignKey(blank=True, help_text='Pastorate (auto-filled from church)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='church_structure.pastorate')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-first_visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('sms', 'SMS/Text Message'), ('home_visit', 'Home Visit'), ('church_visit', 'Church Visit'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20)),
                ('follow_up_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('unsuccessful', 'Unsuccessful'), ('rescheduled', 'Rescheduled')], default='planned', max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='Purpose of follow-up (e.g., Thank you for visiting)', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Follow-up notes and outcome')),
                ('next_follow_up_date', models.DateField(blank=True, help_text='Schedule next follow-up', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_follow_ups', to='email_system.emailcampaign')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='visitors.visitor')),
            ],
            options={
                'verbose_name': 'Visitor Follow-Up',
                'verbose_name_plural': 'Visitor Follow-Ups',
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('church', 'Church Level'), ('pastorate', 'Pastorate Level'), ('diocese', 'Diocese Level'), ('dean', 'Dean/Headquarters Level')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_visitors', models.IntegerField(default=0)),
                ('first_time_visitors', models.IntegerField(default=0)),
                ('return_visitors', models.IntegerField(default=0)),
                ('converted_to_members', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('youth_count', models.IntegerField(default=0)),
                ('adult_count', models.IntegerField(default=0)),
                ('elder_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church_structure.church')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church_structure.diocese')),
                ('pastorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church_structure.pastorate')),
            ],
            options={
                'verbose_name': 'Visitor Statistics',
                'verbose_name_plural': 'Visitor Statistics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='VisitorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField(help_text='Visit number (2, 3, 4, etc.)')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(choices=[('sabbath', 'Saturday Sabbath Service'), ('weekday', 'Weekday Service'), ('event', 'Special Event/Crusade'), ('meeting', 'Meeting'), ('counseling', 'Counseling Session'), ('other', 'Other')], default='sabbath', max_length=20)),
                ('service_attended', models.CharField(blank=True, help_text='Service/event attended (e.g., 9:00 AM Sabbath)', max_length=200)),
                ('came_with', models.CharField(blank=True, help_text='Who they came with', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes about this visit')),
                ('email_sent', models.BooleanField(default=False, help_text='Follow-up email sent for this visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor')),
            ],
            options={
                'verbose_name': 'Visitor Visit',
                'verbose_name_plural': 'Visitor Visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['identifier'], name='visitors_vi_identif_d2eee7_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['phone_number'], name='visitors_vi_phone_n_f99e12_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['email_address'], name='visitors_vi_email_a_d43e32_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['-first_visit_date'], name='visitors_vi_first_v_af59c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitorvisit',
            unique_together={('visitor', 'visit_number')},
        ),
    ]
