# Generated by Django 5.2.4 on 2025-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_purpose', models.CharField(choices=[('service', 'Church Service'), ('event', 'Special Event'), ('meeting', 'Meeting'), ('counseling', 'Counseling'), ('other', 'Other')], default='service', max_length=20)),
                ('invited_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
