# Generated by Django 5.2.4 on 2025-09-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_sms', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='members.member'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bulk_sms.smscampaign'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulk_sms.smstemplate'),
        ),
    ]
