# Generated by Django 5.2.4 on 2025-07-31 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_group', models.CharField(choices=[('Youth', 'Youth'), ('Adult', 'Adult'), ('Elder', 'Elder'), ('Clergy', 'Clergy')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('job_occupation_income', models.TextField(help_text='Job title, occupation details, and income information')),
                ('baptismal_first_name', models.CharField(max_length=100)),
                ('baptismal_last_name', models.CharField(max_length=100)),
                ('date_baptized', models.DateField()),
                ('date_joined_religion', models.DateField()),
                ('date_joined_app', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_home_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.church')),
                ('user_home_diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.diocese')),
                ('user_home_pastorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.pastorate')),
                ('user_town_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_members', to='church_structure.church')),
                ('user_town_diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_members', to='church_structure.diocese')),
                ('user_town_pastorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_members', to='church_structure.pastorate')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
