# Generated by Django 5.2.4 on 2025-09-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('identifier', models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True)),
                ('user_group', models.CharField(choices=[('Youth', 'Youth'), ('Adult', 'Adult'), ('Elder', 'Elder')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=20)),
                ('location', models.CharField(help_text='Location (city, country)', max_length=200)),
                ('education_level', models.CharField(choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='other', max_length=20)),
                ('member_roles', models.JSONField(default=list, help_text='List of member roles')),
                ('church_clergy_roles', models.JSONField(blank=True, default=list, help_text='Church/Dean clergy roles (only if clergy role is selected)')),
                ('special_clergy_roles', models.JSONField(blank=True, default=list, help_text='Special clergy roles (only if clergy role is selected)')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, unique=True)),
                ('job_occupations', models.JSONField(default=list, help_text='List of selected job/occupation roles')),
                ('income_details', models.TextField(blank=True, help_text='Additional income and occupation details')),
                ('baptismal_first_name', models.CharField(max_length=100)),
                ('baptismal_last_name', models.CharField(max_length=100)),
                ('date_baptized', models.DateField()),
                ('date_joined_religion', models.DateField()),
                ('date_joined_app', models.DateField(auto_now_add=True)),
                ('emergency_contact_1_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_1_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_1_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_1_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_2_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_2_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_2_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_2_email', models.EmailField(blank=True, max_length=254)),
                ('membership_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Left/Quit', 'Left/Quit'), ('Dead', 'Dead')], default='Active', max_length=20)),
                ('is_pwd', models.BooleanField(default=False, verbose_name='Person with Disability')),
                ('pwd_type', models.CharField(blank=True, choices=[('prefer_not_to_say', 'Prefer not to say'), ('blind_low_vision', 'Blind or low vision'), ('cognitive_autism', 'Cognitive or Autism'), ('cripple_mobility', 'Cripple or Mobility problem'), ('chronic_invisible', 'Chronic/Invisible Disability'), ('deaf_hearing', 'Deaf or Hearing difficulty'), ('mute_speaking', 'Mute or Speaking difficulty'), ('mental_health', 'Mental Health Condition'), ('other', 'Other (Please specify if you are comfortable)')], max_length=50, verbose_name='Type of Disability')),
                ('pwd_other_description', models.TextField(blank=True, verbose_name='Other Disability Description')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Member')),
                ('is_ordained', models.BooleanField(default=False, verbose_name='Ordained Member')),
                ('profile_photo', models.URLField(blank=True, help_text='Member photo URL', null=True)),
                ('profile_photo_url', models.URLField(blank=True, help_text='Alternative to uploading a photo')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Store custom member data as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nephews_nieces_as_aunt', to='members.member')),
                ('brother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings_as_brother', to='members.member')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='members.member')),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='members.member')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_guardian', to='members.member')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='members.member')),
                ('sister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings_as_sister', to='members.member')),
                ('uncle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nephews_nieces_as_uncle', to='members.member')),
                ('user_home_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.church')),
                ('user_home_diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.diocese')),
                ('user_home_pastorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.pastorate')),
                ('user_town_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_members', to='church_structure.church')),
                ('user_town_diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_members', to='church_structure.diocese')),
                ('user_town_pastorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='town_members', to='church_structure.pastorate')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('baptism_certificate', 'Baptism Certificate'), ('annual_tithe_card', 'Annual Tithe Card'), ('id_document', 'ID Document'), ('medical_record', 'Medical Record'), ('membership_certificate', 'Membership Certificate'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='member_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Document',
                'verbose_name_plural': 'Member Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
