# Generated by Django 5.2.4 on 2025-07-31 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Store custom member data as key-value pairs'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_1_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_1_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_1_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_1_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_2_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_2_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading a photo'),
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('baptism_certificate', 'Baptism Certificate'), ('annual_tithe_card', 'Annual Tithe Card'), ('id_document', 'ID Document'), ('medical_record', 'Medical Record'), ('membership_certificate', 'Membership Certificate'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='member_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Document',
                'verbose_name_plural': 'Member Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
