# Generated by Django 5.2.4 on 2025-10-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account for member login access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload member photo', null=True, upload_to='member_photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading - provide image URL (e.g., https://i.imgur.com/BUxE9oF.jpeg)'),
        ),
    ]
