# Generated by Django 5.2.4 on 2025-10-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_structure', '0002_initial'),
        ('members', '0002_member_user_alter_member_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_home_church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.church'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_home_diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.diocese'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_home_pastorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_members', to='church_structure.pastorate'),
        ),
    ]
