# Generated by Django 5.2.4 on 2025-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='education_level',
            field=models.CharField(choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(choices=[('siaya', 'Siaya'), ('nairobi', 'Nairobi'), ('kisumu', 'Kisumu'), ('mombasa', 'Mombasa'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=20),
        ),
    ]
