# Generated by Django 5.2.4 on 2025-08-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_education_level_member_gender_member_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.AddField(
            model_name='member',
            name='aunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nephews_nieces_as_aunt', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings_as_brother', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_guardian', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_ordained',
            field=models.BooleanField(default=False, verbose_name='Ordained Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_pwd',
            field=models.BooleanField(default=False, verbose_name='Person with Disability'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Left/Quit', 'Left/Quit'), ('Dead', 'Dead')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='pwd_other_description',
            field=models.TextField(blank=True, verbose_name='Other Disability Description'),
        ),
        migrations.AddField(
            model_name='member',
            name='pwd_type',
            field=models.CharField(blank=True, choices=[('prefer_not_to_say', 'Prefer not to say'), ('blind_low_vision', 'Blind or low vision'), ('cognitive_autism', 'Cognitive or Autism'), ('cripple_mobility', 'Cripple or Mobility problem'), ('chronic_invisible', 'Chronic/Invisible Disability'), ('deaf_hearing', 'Deaf or Hearing difficulty'), ('mute_speaking', 'Mute or Speaking difficulty'), ('mental_health', 'Mental Health Condition'), ('other', 'Other (Please specify if you are comfortable)')], max_length=50, verbose_name='Type of Disability'),
        ),
        migrations.AddField(
            model_name='member',
            name='sister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings_as_sister', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='uncle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nephews_nieces_as_uncle', to='members.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
