# Generated by Django 5.2.4 on 2025-11-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_user_home_church_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='aunt',
        ),
        migrations.RemoveField(
            model_name='member',
            name='brother',
        ),
        migrations.RemoveField(
            model_name='member',
            name='father',
        ),
        migrations.RemoveField(
            model_name='member',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='member',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sister',
        ),
        migrations.RemoveField(
            model_name='member',
            name='uncle',
        ),
        migrations.AddField(
            model_name='member',
            name='aunts',
            field=models.JSONField(blank=True, default=list, help_text='List of aunts'),
        ),
        migrations.AddField(
            model_name='member',
            name='brothers',
            field=models.JSONField(blank=True, default=list, help_text='List of brothers'),
        ),
        migrations.AddField(
            model_name='member',
            name='fathers',
            field=models.JSONField(blank=True, default=list, help_text='List of fathers (biological, baptismal, hand ordination)'),
        ),
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.JSONField(blank=True, default=list, help_text='List of friends'),
        ),
        migrations.AddField(
            model_name='member',
            name='guardians',
            field=models.JSONField(blank=True, default=list, help_text='List of guardians'),
        ),
        migrations.AddField(
            model_name='member',
            name='mothers',
            field=models.JSONField(blank=True, default=list, help_text='List of mothers (biological, baptismal, hand ordination)'),
        ),
        migrations.AddField(
            model_name='member',
            name='sisters',
            field=models.JSONField(blank=True, default=list, help_text='List of sisters'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.JSONField(blank=True, default=dict, help_text='Spouse information (husband/wife)'),
        ),
        migrations.AddField(
            model_name='member',
            name='uncles',
            field=models.JSONField(blank=True, default=list, help_text='List of uncles'),
        ),
    ]
