# Generated by Django 5.2.4 on 2025-08-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_is_active_member_aunt_member_brother_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='identifier',
            field=models.CharField(blank=True, help_text='Auto-generated unique identifier', max_length=20, unique=True),
        ),
    ]
