# Generated by Django 5.2.4 on 2025-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_add_member_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_group',
            field=models.CharField(choices=[('Youth', 'Youth'), ('Adult', 'Adult'), ('Elder', 'Elder')], max_length=20),
        ),
    ]
