# Generated by Django 5.2.4 on 2025-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_update_location_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.URLField(blank=True, help_text='Member photo URL', null=True),
        ),
    ]
