# Generated by Django 5.2.4 on 2025-11-21 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_structure', '0002_initial'),
        ('members', '0004_remove_member_aunt_remove_member_brother_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(blank=True, help_text='Auto-generated session code (e.g., RUWE-SESS-XXXX-XXXX)', max_length=20, unique=True)),
                ('session_name', models.CharField(help_text='Session name (e.g., Sabbath Service - Jan 15, 2025)', max_length=200)),
                ('session_type', models.CharField(choices=[('sabbath', 'Saturday Sabbath Service'), ('weekday', 'Weekday Service'), ('prayer_meeting', 'Prayer Meeting'), ('bible_study', 'Bible Study'), ('youth_service', 'Youth Service'), ('special_event', 'Special Event'), ('pastorate_gathering', 'Pastorate Gathering'), ('diocese_gathering', 'Diocese Gathering'), ('dean_gathering', 'Dean/Headquarters Gathering')], default='sabbath', max_length=30)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('service_time', models.CharField(choices=[('6:00 AM', '6:00 AM Saturday'), ('9:00 AM', '9:00 AM Saturday'), ('12:00 PM', '12:00 PM Saturday'), ('3:00 PM', '3:00 PM Saturday'), ('Other', 'Other Time')], default='9:00 AM', max_length=20)),
                ('level', models.CharField(choices=[('church', 'Church Level'), ('pastorate', 'Pastorate Level'), ('diocese', 'Diocese Level'), ('dean', 'Dean/Headquarters Level')], default='church', max_length=20)),
                ('is_dean_session', models.BooleanField(default=False, help_text='Session at Dean/Headquarters level', verbose_name='Dean/Headquarters Session')),
                ('location', models.CharField(blank=True, help_text='Specific location/venue', max_length=300)),
                ('topic', models.CharField(blank=True, help_text='Sermon/teaching topic', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Session notes')),
                ('total_expected', models.IntegerField(default=0, help_text='Expected attendance count')),
                ('total_present', models.IntegerField(default=0, help_text='Present count')),
                ('total_apology', models.IntegerField(default=0, help_text='Apology count')),
                ('total_absent', models.IntegerField(default=0, help_text='Absent count')),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Lock session to prevent further changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, help_text='Church (for church-level sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='church_structure.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diocese', models.ForeignKey(blank=True, help_text='Diocese (for diocese-level sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='church_structure.diocese')),
                ('pastorate', models.ForeignKey(blank=True, help_text='Pastorate (for pastorate-level sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='church_structure.pastorate')),
                ('preacher', models.ForeignKey(blank=True, help_text='Who preached/led this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preached_sessions', to='members.member')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-session_date', '-service_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('apology', 'Apology'), ('absent', 'Absent')], default='present', max_length=10)),
                ('check_in_time', models.TimeField(blank=True, help_text='Time member checked in (if present)', null=True)),
                ('apology_reason', models.TextField(blank=True, help_text='Reason for apology (if applicable)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['member__last_name', 'member__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('church', 'Church Level'), ('pastorate', 'Pastorate Level'), ('diocese', 'Diocese Level'), ('dean', 'Dean/Headquarters Level')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_attendance_records', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_apology', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Average attendance percentage', max_digits=5)),
                ('active_members', models.IntegerField(default=0, help_text='Members who attended at least once')),
                ('inactive_members', models.IntegerField(default=0, help_text='Members with 3+ consecutive absences')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church_structure.church')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church_structure.diocese')),
                ('pastorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church_structure.pastorate')),
            ],
            options={
                'verbose_name': 'Attendance Statistics',
                'verbose_name_plural': 'Attendance Statistics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive absence count')),
                ('last_absence_date', models.DateField(blank=True, null=True)),
                ('last_present_date', models.DateField(blank=True, null=True)),
                ('email_sent_for_3_absences', models.BooleanField(default=False)),
                ('email_sent_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(help_text='Church where absences are tracked', on_delete=django.db.models.deletion.CASCADE, related_name='absence_streaks', to='church_structure.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_streaks', to='members.member')),
            ],
            options={
                'verbose_name': 'Absence Streak',
                'verbose_name_plural': 'Absence Streaks',
                'unique_together': {('member', 'church')},
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_code'], name='attendance__session_d86d46_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['-session_date'], name='attendance__session_147302_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['level'], name='attendance__level_e3da40_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-marked_at'], name='attendance__marked__2b73d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'member')},
        ),
    ]
