# Generated by Django 5.2.4 on 2025-09-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.service'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('service', 'member')},
        ),
    ]
