# Generated by Django 5.2.4 on 2025-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RuweHolyGhostChurch', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('pastor_name', models.CharField(max_length=200)),
                ('pastor_phone', models.CharField(blank=True, max_length=20)),
                ('pastor_email', models.EmailField(blank=True, max_length=254)),
                ('sunday_morning_service', models.TimeField(default='09:00')),
                ('sunday_evening_service', models.TimeField(default='18:00')),
                ('wednesday_service', models.TimeField(default='19:00')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('enable_sms', models.BooleanField(default=True)),
                ('sms_sender_name', models.CharField(blank=True, max_length=11)),
                ('auto_backup', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='church/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Information',
                'verbose_name_plural': 'Church Information',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_notifications', models.BooleanField(default=True)),
                ('anniversary_notifications', models.BooleanField(default=True)),
                ('attendance_reminders', models.BooleanField(default=True)),
                ('follow_up_reminders', models.BooleanField(default=True)),
                ('smtp_server', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sms_api_key', models.CharField(blank=True, max_length=200)),
                ('sms_api_secret', models.CharField(blank=True, max_length=200)),
                ('sms_provider', models.CharField(default='twilio', max_length=50)),
                ('backup_frequency', models.CharField(default='weekly', max_length=20)),
                ('backup_location', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
