# Generated by Django 5.2.4 on 2025-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchinfo',
            name='banner_image',
            field=models.URLField(blank=True, help_text='Church banner image URL', null=True),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='logo',
            field=models.URLField(blank=True, help_text='Church logo URL', null=True),
        ),
    ]
